import type { EquipmentSlotConfig, ItemTemplate } from './types'

export const IS_MOBILE = typeof window !== 'undefined' ? window.innerWidth < 1280 : false

export const CELL_SIZE = IS_MOBILE ? 32 : 50

export const EQUIPMENT_SLOTS: EquipmentSlotConfig[] = [
  { id: 'helmet', label: 'HEAD', accepts: ['helmet'], x: 0, y: 0 },
  { id: 'armor', label: 'BODY', accepts: ['armor'], x: 0, y: 1 },
  { id: 'primary', label: 'PRIMARY', accepts: ['weapon'], x: 1, y: 0 },
  { id: 'secondary', label: 'SECONDARY', accepts: ['weapon'], x: 1, y: 1 },
  { id: 'backpack', label: 'BACK', accepts: ['backpack'], x: 2, y: 0 },
  { id: 'rig', label: 'RIG', accepts: ['rig'], x: 2, y: 1 },
  { id: 'pocket1', label: '', accepts: ['medical', 'ammo', 'material'], x: 0, y: 0 },
  { id: 'pocket2', label: '', accepts: ['medical', 'ammo', 'material'], x: 1, y: 0 },
  { id: 'pocket3', label: '', accepts: ['medical', 'ammo', 'material'], x: 0, y: 1 },
  { id: 'pocket4', label: '', accepts: ['medical', 'ammo', 'material'], x: 1, y: 1 },
]

export const ITEM_TEMPLATES: Record<string, ItemTemplate> = {
  'ar-15': {
    id: 'ar-15',
    name: 'TR-4 Assault Rifle',
    description: 'Standard issue tactical rifle. Reliable kinetic damage.',
    type: 'weapon',
    width: 4,
    height: 2,
    rarity: 'rare',
    weight: 3.5,
    stackable: false,
    maxStack: 1,
    image: 'https://picsum.photos/seed/ar15/200/100',
    stats: { damage: 45, ergonomics: 60 },
  },
  pistol: {
    id: 'pistol',
    name: 'P-99 Sidearm',
    description: 'Compact pistol for close quarters.',
    type: 'weapon',
    width: 2,
    height: 1,
    rarity: 'common',
    weight: 1.2,
    stackable: false,
    maxStack: 1,
    image: 'https://picsum.photos/seed/pistol/100/50',
    stats: { damage: 22, ergonomics: 85 },
  },
  medkit: {
    id: 'medkit',
    name: 'AFAK Medkit',
    description: 'Advanced First Aid Kit. Stops bleeding.',
    type: 'medical',
    width: 1,
    height: 2,
    rarity: 'common',
    weight: 0.8,
    stackable: false,
    maxStack: 1,
    image: 'https://picsum.photos/seed/medkit/50/100',
  },
  ammo_box: {
    id: 'ammo_box',
    name: '5.56mm Ammo',
    description: 'Armor piercing rounds.',
    type: 'ammo',
    width: 1,
    height: 1,
    rarity: 'common',
    weight: 0.5,
    stackable: true,
    maxStack: 60,
    image: 'https://picsum.photos/seed/ammo/50/50',
  },
  helmet_heavy: {
    id: 'helmet_heavy',
    name: 'Altyn Helmet',
    description: 'Heavy titanium helmet with face shield.',
    type: 'helmet',
    width: 2,
    height: 2,
    rarity: 'epic',
    weight: 4.2,
    stackable: false,
    maxStack: 1,
    image: 'https://picsum.photos/seed/helmet/100/100',
    stats: { defense: 80 },
  },
  armor_light: {
    id: 'armor_light',
    name: 'Trooper Armor',
    description: 'Lightweight poly-plate armor.',
    type: 'armor',
    width: 2,
    height: 2,
    rarity: 'rare',
    weight: 5.5,
    stackable: false,
    maxStack: 1,
    image: 'https://picsum.photos/seed/vest/100/100',
    stats: { defense: 55 },
  },
  backpack_large: {
    id: 'backpack_large',
    name: 'Tri-Zip Backpack',
    description: 'Large tactical backpack. Adds 5x5 storage.',
    type: 'backpack',
    width: 3,
    height: 4,
    rarity: 'rare',
    weight: 1.5,
    stackable: false,
    maxStack: 1,
    image: 'https://picsum.photos/seed/backpack/150/200',
  },
  gold_watch: {
    id: 'gold_watch',
    name: 'Antique Watch',
    description: 'Valuable keepsake from the old world.',
    type: 'material',
    width: 1,
    height: 1,
    rarity: 'legendary',
    weight: 0.2,
    stackable: false,
    maxStack: 1,
    image: 'https://picsum.photos/seed/watch/50/50',
    questItem: true,
  },
}

