/**
 * Unified Item Templates
 * =====================================================
 * Single source of truth for all item definitions.
 * Used by both client and server (server copies during build).
 * =====================================================
 */

import type { ItemTemplate } from './itemTypes'

export const ITEM_TEMPLATES: Record<string, ItemTemplate> = {
    // ============ WEAPONS - MELEE ============
    rusty_sword: {
        id: 'rusty_sword',
        name: 'Ржавый меч',
        description: 'Старый железный меч, зазубренный и тупой. Лучше, чем голыми руками.',
        kind: 'weapon',
        rarity: 'common',
        icon: '⚔️',
        baseStats: { damage: 12, weight: 2.5, width: 1, height: 3, maxDurability: 50 },
        tags: ['melee', 'slashing'],
    },
    rusty_pipe: {
        id: 'rusty_pipe',
        name: 'Ржавая труба',
        description: 'Тяжелая, корродированная железная труба. Грубо, но эффективно.',
        kind: 'weapon',
        rarity: 'common',
        icon: 'pipe',
        baseStats: { damage: 8, weight: 2.0, width: 1, height: 3, maxDurability: 40 },
        tags: ['melee', 'blunt'],
        combatWeaponId: 'rusty_pipe',
    },
    lead_pipe: {
        id: 'lead_pipe',
        name: 'Свинцовая труба',
        description: 'Тяжелая, корродированная свинцовая труба. Грубо, но эффективно.',
        kind: 'weapon',
        rarity: 'common',
        icon: 'pipe',
        baseStats: { damage: 8, weight: 3.0, width: 1, height: 3, maxDurability: 50 },
        tags: ['melee', 'crushing'],
    },
    kitchen_knife: {
        id: 'kitchen_knife',
        name: 'Кухонный нож',
        description: 'Стандартный кухонный нож. Острый, но хрупкий.',
        kind: 'weapon',
        rarity: 'common',
        icon: '🔪',
        baseStats: { damage: 5, weight: 0.5, width: 1, height: 2, maxDurability: 30 },
        tags: ['melee', 'piercing'],
    },
    sledgehammer: {
        id: 'sledgehammer',
        name: 'Кувалда',
        description: 'Тяжелый промышленный инструмент. Разрушительный удар.',
        kind: 'weapon',
        rarity: 'uncommon',
        icon: '🔨',
        baseStats: { damage: 14, weight: 8.0, width: 2, height: 4, maxDurability: 80 },
        tags: ['melee', 'crushing', 'two_handed'],
    },
    broken_bottle: {
        id: 'broken_bottle',
        name: 'Разбитая бутылка',
        description: 'Острые осколки стекла. Вызывает кровотечение.',
        kind: 'weapon',
        rarity: 'common',
        icon: '🍾',
        baseStats: { damage: 4, weight: 0.2, width: 1, height: 1, maxDurability: 5 },
        tags: ['melee', 'slashing'],
    },
    knife: {
        id: 'knife',
        name: 'Выкидной нож',
        description: 'Скрытный и острый.',
        kind: 'weapon',
        rarity: 'common',
        icon: '🗡',
        baseStats: { damage: 6, weight: 0.5, width: 1, height: 1, maxDurability: 40 },
        tags: ['melee', 'stealth'],
        combatWeaponId: 'combat_knife',
    },
    wrench: {
        id: 'wrench',
        name: 'Разводной ключ',
        description: 'Хорош для ремонта, или чтобы что-нибудь сломать.',
        kind: 'weapon',
        rarity: 'common',
        icon: '🔧',
        baseStats: { damage: 10, weight: 2, width: 1, height: 2, maxDurability: 60 },
        tags: ['melee', 'tool'],
        combatWeaponId: 'wrench',
    },

    // ============ WEAPONS - RANGED ============
    glock_19: {
        id: 'glock_19',
        name: 'Glock 19',
        description: 'Надежный 9мм пистолет. Стандартное вооружение.',
        kind: 'weapon',
        rarity: 'rare',
        icon: '🔫',
        baseStats: { damage: 10, weight: 1.5, width: 2, height: 2, maxDurability: 100 },
        tags: ['ranged', 'ballistic', 'pistol'],
        combatWeaponId: 'glock_19',
    },
    pistol_pm: {
        id: 'pistol_pm',
        name: 'Пистолет ПМ',
        description: 'Пистолет Макарова. Надежное личное оружие.',
        kind: 'weapon',
        rarity: 'common',
        icon: '🔫',
        baseStats: { damage: 8, weight: 1.5, width: 2, height: 1, maxDurability: 100 },
        tags: ['ranged', 'pistol'],
        combatWeaponId: 'makarov',
    },
    sawed_off_shotgun: {
        id: 'sawed_off_shotgun',
        name: 'Обрез',
        description: 'Модифицирован для ближнего боя. Большой разброс.',
        kind: 'weapon',
        rarity: 'rare',
        icon: '💥',
        baseStats: { damage: 18, weight: 2.5, width: 3, height: 2, maxDurability: 80 },
        tags: ['ranged', 'ballistic', 'shotgun'],
        combatWeaponId: 'sawed_off',
    },
    rifle_ak74: {
        id: 'rifle_ak74',
        name: 'AK-74',
        description: 'Надежная штурмовая винтовка. Калибр 5.45мм.',
        kind: 'weapon',
        rarity: 'rare',
        icon: '🔫',
        baseStats: { damage: 25, weight: 3.5, width: 3, height: 2, maxDurability: 90 },
        tags: ['ranged', 'rifle', 'two_handed'],
        combatWeaponId: 'ak_74',
    },
    sniper_rifle: {
        id: 'sniper_rifle',
        name: 'Снайперская винтовка СВД',
        description: 'Полуавтоматическая снайперская винтовка. Точность на дальних дистанциях.',
        kind: 'weapon',
        rarity: 'epic',
        icon: '🔫',
        imageUrl: '/images/weapons/патронвинтовка.png',
        baseStats: { damage: 35, weight: 4.5, width: 4, height: 2, maxDurability: 85 },
        tags: ['ranged', 'rifle', 'sniper', 'two_handed'],
        combatWeaponId: 'svd',
    },
    grenade: {
        id: 'grenade',
        name: 'Осколочная граната РГД-5',
        description: 'Стандартная советская осколочная граната. Радиус поражения 25 метров.',
        kind: 'consumable',
        rarity: 'rare',
        icon: '💣',
        imageUrl: '/images/weapons/бомба.png',
        baseStats: { damage: 50, weight: 0.3, width: 1, height: 1 },
        tags: ['explosive', 'throwable'],
    },

    // ============ EQUIPMENT - TECH ============
    field_scanner: {
        id: 'field_scanner',
        name: 'Полевой сканер «Око»',
        description: 'Многофункциональный сканер для анализа биологических и химических образцов.',
        kind: 'tool',
        rarity: 'rare',
        icon: '📡',
        baseStats: { weight: 0.8, width: 2, height: 1 },
        tags: ['tool', 'scanner', 'tech'],
    },
    tactical_drone: {
        id: 'tactical_drone',
        name: 'Тактический дрон «Глаз»',
        description: 'Компактный разведывательный дрон с камерой. Радиус действия — 200 метров.',
        kind: 'tool',
        rarity: 'epic',
        icon: '🛸',
        baseStats: { weight: 1.2, width: 2, height: 2 },
        tags: ['tool', 'drone', 'tech', 'recon'],
    },
    emp_charge: {
        id: 'emp_charge',
        name: 'ЭМИ-заряд',
        description: 'Электромагнитный импульс. Выводит из строя электронику в радиусе 10 метров.',
        kind: 'consumable',
        rarity: 'rare',
        icon: '⚡',
        imageUrl: '/images/weapons/бомба2.png',
        baseStats: { weight: 0.4, width: 1, height: 1 },
        tags: ['explosive', 'tech', 'emp'],
    },

    // ============ ARMOR - VESTS ============
    vest_class1: {
        id: 'vest_class1',
        name: 'Бронежилет 1 класса',
        description: 'Лёгкий защитный жилет. Защищает от осколков и мелкого калибра.',
        kind: 'armor',
        rarity: 'common',
        icon: '🦺',
        imageUrl: '/images/Защита/Бронижилет1Класса.png',
        baseStats: { defense: 10, weight: 2.5, width: 3, height: 3, maxDurability: 60 },
        tags: ['armor', 'vest'],
    },
    vest_class2: {
        id: 'vest_class2',
        name: 'Бронежилет 2 класса',
        description: 'Стандартный бронежилет. Защита от пистолетных калибров.',
        kind: 'armor',
        rarity: 'uncommon',
        icon: '🦺',
        imageUrl: '/images/Защита/Бронежилет2класса.png',
        baseStats: { defense: 18, weight: 4.0, width: 3, height: 3, maxDurability: 80 },
        tags: ['armor', 'vest'],
    },
    vest_class3: {
        id: 'vest_class3',
        name: 'Бронежилет 3 класса',
        description: 'Усиленный бронежилет с керамическими пластинами. Защита от автоматного огня.',
        kind: 'armor',
        rarity: 'rare',
        icon: '🦺',
        imageUrl: '/images/Защита/Бронежилет3класса.png',
        baseStats: { defense: 28, weight: 6.5, width: 3, height: 3, maxDurability: 100 },
        tags: ['armor', 'vest', 'heavy'],
    },
    vest_class4: {
        id: 'vest_class4',
        name: 'Бронежилет 4 класса',
        description: 'Тяжёлый штурмовой бронежилет. Выдерживает бронебойные патроны.',
        kind: 'armor',
        rarity: 'epic',
        icon: '🦺',
        imageUrl: '/images/Защита/Бронежилет4класса.png',
        baseStats: { defense: 40, weight: 9.0, width: 3, height: 3, maxDurability: 120 },
        tags: ['armor', 'vest', 'heavy'],
    },

    // ============ ARMOR - HELMETS ============
    helmet_class1: {
        id: 'helmet_class1',
        name: 'Шлем 1 класса',
        description: 'Полевая каска. Базовая защита головы.',
        kind: 'armor',
        rarity: 'common',
        icon: '⛑',
        imageUrl: '/images/Защита/Шлем1класса.png',
        baseStats: { defense: 5, weight: 1.0, width: 2, height: 2, maxDurability: 40 },
        tags: ['armor', 'head'],
    },
    helmet_class2: {
        id: 'helmet_class2',
        name: 'Шлем 2 класса',
        description: 'Композитный шлем с мягкой подкладкой.',
        kind: 'armor',
        rarity: 'uncommon',
        icon: '⛑',
        imageUrl: '/images/Защита/Шлем2Класса.png',
        baseStats: { defense: 10, weight: 1.5, width: 2, height: 2, maxDurability: 60 },
        tags: ['armor', 'head'],
    },
    helmet_class3: {
        id: 'helmet_class3',
        name: 'Шлем 3 класса',
        description: 'Тактический шлем с забралом и креплениями для ПНВ.',
        kind: 'armor',
        rarity: 'rare',
        icon: '⛑',
        imageUrl: '/images/Защита/Шлем3касса.png',
        baseStats: { defense: 15, weight: 2.0, width: 2, height: 2, maxDurability: 80 },
        tags: ['armor', 'head'],
    },
    helmet_class4: {
        id: 'helmet_class4',
        name: 'Шлем 4 класса',
        description: 'Штурмовой шлем с полной защитой лица.',
        kind: 'armor',
        rarity: 'epic',
        icon: '⛑',
        imageUrl: '/images/Защита/Шлем4класса.png',
        baseStats: { defense: 22, weight: 2.5, width: 2, height: 2, maxDurability: 100 },
        tags: ['armor', 'head'],
    },
    vest_police: {
        id: 'vest_police',
        name: 'Полицейский жилет',
        description: 'Стандартный кевларовый жилет. Обеспечивает неплохую защиту.',
        kind: 'armor',
        rarity: 'uncommon',
        icon: '🦺',
        baseStats: { defense: 15, weight: 4, width: 3, height: 3, maxDurability: 80 },
        tags: ['armor'],
    },
    helmet_police: {
        id: 'helmet_police',
        name: 'Шлем спецназа',
        description: 'Тяжелый шлем с забралом.',
        kind: 'armor',
        rarity: 'uncommon',
        icon: '⛑',
        baseStats: { defense: 10, weight: 2, width: 2, height: 2, maxDurability: 60 },
        tags: ['armor', 'head'],
    },

    // ============ AMMO ============
    ammo_pistol: {
        id: 'ammo_pistol',
        name: 'Патроны 9×18 ПМ',
        description: 'Стандартные пистолетные патроны. Магазин 16 шт.',
        kind: 'consumable',
        rarity: 'common',
        icon: '🔫',
        baseStats: { weight: 0.2, width: 1, height: 1 },
        tags: ['ammo', 'pistol'],
    },
    ammo_rifle: {
        id: 'ammo_rifle',
        name: 'Патроны 7.62×39',
        description: 'Автоматные патроны для АК. Магазин 30 шт.',
        kind: 'consumable',
        rarity: 'uncommon',
        icon: '🔫',
        baseStats: { weight: 0.5, width: 1, height: 1 },
        tags: ['ammo', 'rifle'],
    },
    ammo_sniper: {
        id: 'ammo_sniper',
        name: 'Патроны 7.62×54R',
        description: 'Снайперские патроны для СВД. Магазин 10 шт.',
        kind: 'consumable',
        rarity: 'rare',
        icon: '🎯',
        baseStats: { weight: 0.3, width: 1, height: 1 },
        tags: ['ammo', 'sniper'],
    },

    // ============ SUBMACHINE GUNS ============
    smg_mp_class1: {
        id: 'smg_mp_class1',
        name: 'Пистолет-пулемёт MP5',
        description: 'Компактный ПП. Высокая скорострельность, малый калибр.',
        kind: 'weapon',
        rarity: 'uncommon',
        icon: '🔫',
        imageUrl: '/images/weapons/MP1класса.png',
        baseStats: { damage: 12, weight: 2.5, width: 3, height: 1, maxDurability: 70 },
        tags: ['ranged', 'smg', 'two_handed'],
        combatWeaponId: 'mp5',
    },

    jacket_hidden: {
        id: 'jacket_hidden',
        name: 'Куртка контрабандиста',
        description: 'Куртка со скрытой подкладкой.',
        kind: 'armor',
        rarity: 'uncommon',
        icon: '🧥',
        baseStats: { defense: 3, weight: 2, width: 2, height: 2 },
        tags: ['clothing', 'stealth'],
    },

    // ============ CLOTHING ============
    scout_jacket: {
        id: 'scout_jacket',
        name: 'Куртка разведчика',
        description: 'Легкая куртка со скрытыми карманами. Любима бегунами.',
        kind: 'clothing',
        rarity: 'rare',
        icon: '🧥',
        baseStats: { defense: 2, weight: 1.5, width: 2, height: 2 },
        tags: ['clothing', 'stealth'],
    },
    clothing_basic: {
        id: 'clothing_basic',
        name: 'Поношенная одежда',
        description: 'Простая, удобная одежда. Видала виды.',
        kind: 'clothing',
        rarity: 'common',
        icon: '👕',
        baseStats: { weight: 1, width: 2, height: 2, defense: 1 },
        tags: ['clothing'],
    },
    trousers_basic: {
        id: 'trousers_basic',
        name: 'Штаны карго',
        description: 'Прочные штаны с множеством карманов.',
        kind: 'clothing',
        rarity: 'common',
        icon: '👖',
        baseStats: { weight: 1, width: 2, height: 2, defense: 1 },
        tags: ['clothing'],
    },

    // ============ BACKPACKS / RIGS ============
    backpack_medic: {
        id: 'backpack_medic',
        name: 'Медицинская сумка',
        description: 'Специализированный рюкзак с отсеками для медикаментов.',
        kind: 'backpack',
        rarity: 'uncommon',
        icon: '🎒',
        baseStats: {
            weight: 1.5,
            width: 2,
            height: 2,
            capacity: 16,
            containerConfig: { width: 4, height: 4, name: 'Medic Bag' },
        },
        tags: ['backpack'],
    },
    belt_tool: {
        id: 'belt_tool',
        name: 'Пояс с инструментами',
        description: 'Держит инструменты под рукой.',
        kind: 'rig',
        rarity: 'common',
        icon: '🛠',
        baseStats: {
            weight: 1,
            width: 2,
            height: 1,
            capacity: 4,
            containerConfig: { width: 4, height: 1, name: 'Tool Belt' },
        },
        tags: ['rig'],
    },

    // ============ CONSUMABLES ============
    field_medkit: {
        id: 'field_medkit',
        name: 'Полевая аптечка',
        description: 'Стандартный медицинский набор. Восстанавливает HP и останавливает кровотечение.',
        kind: 'consumable',
        rarity: 'uncommon',
        icon: '⛑',
        baseStats: { weight: 1.2, width: 2, height: 2 },
        tags: ['healing'],
    },
    medkit: {
        id: 'medkit',
        name: 'Аптечка первой помощи',
        description: 'Необходима для лечения ран.',
        kind: 'consumable',
        rarity: 'uncommon',
        icon: '⛑',
        baseStats: { weight: 1, width: 1, height: 1 },
        tags: ['healing'],
    },
    bandage: {
        id: 'bandage',
        name: 'Грязный бинт',
        description: 'Лучше, чем ничего, но есть риск инфекции.',
        kind: 'consumable',
        rarity: 'common',
        icon: 'bandage',
        baseStats: { weight: 0.1, width: 1, height: 1 },
        tags: ['healing'],
    },
    pills: {
        id: 'pills',
        name: 'Обезболивающее',
        description: 'Временное облегчение боли.',
        kind: 'consumable',
        rarity: 'common',
        icon: '💊',
        baseStats: { weight: 0.1, width: 1, height: 1 },
        tags: ['healing'],
    },
    ration_pack: {
        id: 'ration_pack',
        name: 'Сухпаек',
        description: 'Позволит продержаться день на границе. На вкус как картон.',
        kind: 'consumable',
        rarity: 'common',
        icon: '🍞',
        baseStats: { weight: 0.6, width: 1, height: 1 },
        tags: ['sustenance'],
    },
    canned_food: {
        id: 'canned_food',
        name: 'Консервированные бобы',
        description: 'Истек срок годности в 2012. Съедобно, наверное.',
        kind: 'consumable',
        rarity: 'common',
        icon: 'can',
        baseStats: { weight: 0.5, width: 1, height: 1 },
        tags: ['sustenance'],
    },

    // ============ ARTIFACTS ============
    mica_shard: {
        id: 'mica_shard',
        name: 'Осколок слюды',
        description: 'Слабо светится при приближении аномалий. Теплый на ощупь.',
        kind: 'artifact',
        rarity: 'epic',
        icon: '🜁',
        baseStats: { weight: 0.2, width: 1, height: 1 },
        tags: ['artifact', 'detection'],
    },

    // ============ MISC / MATERIALS ============
    badge: {
        id: 'badge',
        name: 'Полицейский значок',
        description: 'Потускневший значок. Власть осталась в прошлом.',
        kind: 'misc',
        rarity: 'common',
        icon: '👮',
        baseStats: { weight: 0.1, width: 1, height: 1 },
        tags: ['misc'],
    },
    scrap: {
        id: 'scrap',
        name: 'Металлолом',
        description: 'Полезен для крафта и ремонта.',
        kind: 'misc',
        rarity: 'common',
        icon: '⚙️',
        baseStats: { weight: 0.5, width: 1, height: 1 },
        tags: ['material'],
    },
    cash: {
        id: 'cash',
        name: 'Кредиты',
        description: 'Валюта старого мира. Все еще имеет ценность для некоторых.',
        kind: 'misc',
        rarity: 'common',
        icon: '💵',
        baseStats: { weight: 0, width: 1, height: 1 },
        tags: ['currency'],
    },

    // ============ BACKPACKS ============
    backpack_tactical_medium: {
        id: 'backpack_tactical_medium',
        name: 'Тактический рюкзак (средний)',
        description: 'Стандартный военный рюкзак. Уменьшает вес содержимого на 10%.',
        kind: 'backpack',
        rarity: 'uncommon',
        icon: '🎒',
        imageUrl: '/images/Рюкзаки/ТактическийРюкзак(средний).png',
        baseStats: {
            weight: 2.0,
            width: 3,
            height: 3,
            capacity: 20,
            containerConfig: { width: 5, height: 4, name: 'Tactical Bag' },
        },
        tags: ['backpack', 'weight_reduction_10'],
    },
    backpack_tactical_large: {
        id: 'backpack_tactical_large',
        name: 'Тактический рюкзак (большой)',
        description: 'Увеличенный тактический рюкзак. Уменьшает вес содержимого на 15%.',
        kind: 'backpack',
        rarity: 'rare',
        icon: '🎒',
        imageUrl: '/images/Рюкзаки/ТактическийРюкзак(большой).png',
        baseStats: {
            weight: 3.0,
            width: 3,
            height: 4,
            capacity: 30,
            containerConfig: { width: 6, height: 5, name: 'Large Tactical Bag' },
        },
        tags: ['backpack', 'weight_reduction_15'],
    },
    backpack_hiking_medium: {
        id: 'backpack_hiking_medium',
        name: 'Туристический рюкзак',
        description: 'Удобный туристический рюкзак. Уменьшает вес содержимого на 12%.',
        kind: 'backpack',
        rarity: 'uncommon',
        icon: '🎒',
        imageUrl: '/images/Рюкзаки/ТуристическийРюкзак(большесредний).png',
        baseStats: {
            weight: 2.5,
            width: 3,
            height: 3,
            capacity: 24,
            containerConfig: { width: 6, height: 4, name: 'Hiking Bag' },
        },
        tags: ['backpack', 'weight_reduction_12'],
    },
    backpack_hiking_large: {
        id: 'backpack_hiking_large',
        name: 'Большой туристический рюкзак',
        description: 'Вместительный походный рюкзак. Уменьшает вес содержимого на 18%.',
        kind: 'backpack',
        rarity: 'rare',
        icon: '🎒',
        imageUrl: '/images/Рюкзаки/ТуристическийРюкзак(большой).png',
        baseStats: {
            weight: 3.5,
            width: 4,
            height: 4,
            capacity: 36,
            containerConfig: { width: 6, height: 6, name: 'Large Hiking Bag' },
        },
        tags: ['backpack', 'weight_reduction_18'],
    },
    backpack_expedition: {
        id: 'backpack_expedition',
        name: 'Экспедиционный рюкзак',
        description: 'Огромный рюкзак для длительных походов. Уменьшает вес содержимого на 20%.',
        kind: 'backpack',
        rarity: 'epic',
        icon: '🎒',
        imageUrl: '/images/Рюкзаки/ПоходныйРюкзак(очбольшой).png',
        baseStats: {
            weight: 4.0,
            width: 4,
            height: 5,
            capacity: 50,
            containerConfig: { width: 7, height: 7, name: 'Expedition Bag' },
        },
        tags: ['backpack', 'weight_reduction_20'],
    },
    backpack_medic_large: {
        id: 'backpack_medic_large',
        name: 'Медицинский рюкзак',
        description: 'Специализированный рюкзак для медика. Уменьшает вес мед. предметов на 25%.',
        kind: 'backpack',
        rarity: 'rare',
        icon: '🎒',
        imageUrl: '/images/Рюкзаки/МедРюкзак.png',
        baseStats: {
            weight: 2.5,
            width: 3,
            height: 3,
            capacity: 24,
            containerConfig: { width: 6, height: 4, name: 'Medic Bag' },
        },
        tags: ['backpack', 'weight_reduction_25', 'medical'],
    },

    // ============ DRONES ============
    drone_recon: {
        id: 'drone_recon',
        name: 'Разведывательный дрон',
        description: 'Компактный дрон для разведки. Радиус 300м, время полёта 15 мин.',
        kind: 'tool',
        rarity: 'rare',
        icon: '🛸',
        imageUrl: '/images/Дроны/разведДрон.png',
        baseStats: { weight: 1.5, width: 2, height: 2 },
        tags: ['tool', 'drone', 'recon'],
    },
    drone_bomber: {
        id: 'drone_bomber',
        name: 'Дрон-бомбомёт',
        description: 'Ударный дрон для сброса гранат. Несёт до 2 боеприпасов.',
        kind: 'tool',
        rarity: 'epic',
        icon: '💣',
        imageUrl: '/images/Дроны/ДронБомбомёт.png',
        baseStats: { weight: 3.0, width: 2, height: 2 },
        tags: ['tool', 'drone', 'combat'],
    },
    drone_gunner: {
        id: 'drone_gunner',
        name: 'Дрон-пулемётчик',
        description: 'Боевой дрон с установленным пулемётом. Автоматическое ведение огня.',
        kind: 'tool',
        rarity: 'legendary',
        icon: '🔫',
        imageUrl: '/images/Дроны/ДронПулемёт.png',
        baseStats: { damage: 15, weight: 4.0, width: 3, height: 2 },
        tags: ['tool', 'drone', 'combat'],
    },
    drone_manipulator: {
        id: 'drone_manipulator',
        name: 'Дрон-манипулятор',
        description: 'Инженерный дрон с манипуляторами. Для ремонта и разборки.',
        kind: 'tool',
        rarity: 'epic',
        icon: '🦾',
        imageUrl: '/images/Дроны/ДронМанипулятор.png',
        baseStats: { weight: 2.5, width: 2, height: 2 },
        tags: ['tool', 'drone', 'engineering'],
    },
    drone_rocket: {
        id: 'drone_rocket',
        name: 'Ракетный дрон',
        description: 'Тяжёлый ударный дрон с ракетами. Высокоточное уничтожение.',
        kind: 'tool',
        rarity: 'legendary',
        icon: '🚀',
        imageUrl: '/images/Дроны/Ракетныйдрон.png',
        baseStats: { damage: 50, weight: 5.0, width: 3, height: 2 },
        tags: ['tool', 'drone', 'combat', 'heavy'],
    },

    // ============ GEAR - MEDICAL ============
    gel_healing: {
        id: 'gel_healing',
        name: 'Регенерирующий гель',
        description: 'Биогель для быстрого заживления ран. Восстанавливает HP со временем.',
        kind: 'consumable',
        rarity: 'rare',
        icon: '💉',
        imageUrl: '/images/снаряга/AптечныйГель.png',
        baseStats: { weight: 0.3, width: 1, height: 1 },
        tags: ['healing', 'regen'],
    },
    hp_regen_implant: {
        id: 'hp_regen_implant',
        name: 'Регенератор HP',
        description: 'Имплант для пассивного восстановления здоровья.',
        kind: 'artifact',
        rarity: 'epic',
        icon: '❤️‍🔥',
        imageUrl: '/images/снаряга/Hpрегенерация.png',
        baseStats: { weight: 0.2, width: 1, height: 1 },
        tags: ['implant', 'regen'],
    },
    tourniquet: {
        id: 'tourniquet',
        name: 'Турникет',
        description: 'Останавливает сильное кровотечение. Одноразовый.',
        kind: 'consumable',
        rarity: 'uncommon',
        icon: '🩹',
        imageUrl: '/images/снаряга/Турникет.png',
        baseStats: { weight: 0.1, width: 1, height: 1 },
        tags: ['healing', 'bleeding'],
    },
    bio_analyzer: {
        id: 'bio_analyzer',
        name: 'Биоанализатор',
        description: 'Сканер для анализа биологических образцов и диагностики.',
        kind: 'tool',
        rarity: 'rare',
        icon: '🔬',
        imageUrl: '/images/снаряга/БиоАнализатор.png',
        baseStats: { weight: 0.5, width: 1, height: 1 },
        tags: ['tool', 'medical', 'scanner'],
    },

    // ============ GEAR - TECH ============
    visor_tactical: {
        id: 'visor_tactical',
        name: 'Тактический визор',
        description: 'Обеспечивает HUD с тактической информацией.',
        kind: 'armor',
        rarity: 'rare',
        icon: '🥽',
        imageUrl: '/images/снаряга/Визор.png',
        baseStats: { defense: 2, weight: 0.3, width: 1, height: 1 },
        tags: ['head', 'tech'],
    },
    nvg: {
        id: 'nvg',
        name: 'ПНВ (Прибор ночного видения)',
        description: 'Позволяет видеть в темноте. Крепится на шлем.',
        kind: 'tool',
        rarity: 'rare',
        icon: '👁',
        imageUrl: '/images/снаряга/ПНВ.jpg',
        baseStats: { weight: 0.5, width: 1, height: 1 },
        tags: ['tool', 'vision', 'night'],
    },
    shield_generator: {
        id: 'shield_generator',
        name: 'Генератор щита',
        description: 'Создаёт энергетический щит. Требует энергоячейки.',
        kind: 'tool',
        rarity: 'legendary',
        icon: '🛡',
        imageUrl: '/images/снаряга/ГенераторЩита.png',
        baseStats: { defense: 30, weight: 2.0, width: 2, height: 2 },
        tags: ['tool', 'tech', 'shield'],
    },
    energy_cells: {
        id: 'energy_cells',
        name: 'Энергоячейки',
        description: 'Батареи для питания технических устройств.',
        kind: 'consumable',
        rarity: 'uncommon',
        icon: '🔋',
        imageUrl: '/images/снаряга/ЭнергоЯчейки.png',
        baseStats: { weight: 0.5, width: 1, height: 1 },
        tags: ['energy', 'tech'],
    },
    wave_sensor: {
        id: 'wave_sensor',
        name: 'Датчик волны',
        description: 'Обнаруживает аномальные волновые сигналы.',
        kind: 'tool',
        rarity: 'rare',
        icon: '📡',
        imageUrl: '/images/снаряга/ДатчикВолна.png',
        baseStats: { weight: 0.3, width: 1, height: 1 },
        tags: ['tool', 'detection'],
    },
    radio: {
        id: 'radio',
        name: 'Рация',
        description: 'Для связи с командой на дальних дистанциях.',
        kind: 'tool',
        rarity: 'common',
        icon: '📻',
        imageUrl: '/images/снаряга/рация.jpg',
        baseStats: { weight: 0.4, width: 1, height: 1 },
        tags: ['tool', 'communication'],
    },
    flashlight: {
        id: 'flashlight',
        name: 'Фонарик',
        description: 'Освещает тёмные места. Требует батареи.',
        kind: 'tool',
        rarity: 'common',
        icon: '🔦',
        imageUrl: '/images/снаряга/фонарик.png',
        baseStats: { weight: 0.2, width: 1, height: 1 },
        tags: ['tool', 'light'],
    },

    // ============ GEAR - REPAIR ============
    repair_kit_small: {
        id: 'repair_kit_small',
        name: 'Ремкомплект (малый)',
        description: 'Базовый набор для полевого ремонта.',
        kind: 'consumable',
        rarity: 'common',
        icon: '🔧',
        imageUrl: '/images/снаряга/ремонтныйнабор(малый).png',
        baseStats: { weight: 0.5, width: 1, height: 1 },
        tags: ['repair'],
    },
    repair_kit_medium: {
        id: 'repair_kit_medium',
        name: 'Ремкомплект (средний)',
        description: 'Расширенный набор инструментов для ремонта.',
        kind: 'consumable',
        rarity: 'uncommon',
        icon: '🔧',
        imageUrl: '/images/снаряга/ремонтныйнабор(средний).png',
        baseStats: { weight: 1.0, width: 1, height: 2 },
        tags: ['repair'],
    },
    repair_kit_large: {
        id: 'repair_kit_large',
        name: 'Ремкомплект (большой)',
        description: 'Полный набор для капитального ремонта техники.',
        kind: 'consumable',
        rarity: 'rare',
        icon: '🔧',
        imageUrl: '/images/снаряга/ремонтныйнабор(Большой).png',
        baseStats: { weight: 2.0, width: 2, height: 2 },
        tags: ['repair'],
    },

    // ============ GEAR - AMMO WITH IMAGES ============
    ammo_pistol_mag: {
        id: 'ammo_pistol_mag',
        name: 'Магазин пистолетный',
        description: 'Снаряжённый магазин для пистолета. 16 патронов.',
        kind: 'consumable',
        rarity: 'common',
        icon: '🔫',
        imageUrl: '/images/снаряга/патроныпистолет.png',
        baseStats: { weight: 0.3, width: 1, height: 1 },
        tags: ['ammo', 'pistol'],
    },
    ammo_rifle_mag: {
        id: 'ammo_rifle_mag',
        name: 'Магазин автоматный',
        description: 'Снаряжённый магазин для автомата. 30 патронов.',
        kind: 'consumable',
        rarity: 'uncommon',
        icon: '🔫',
        imageUrl: '/images/снаряга/патроныАвтомат.png',
        baseStats: { weight: 0.6, width: 1, height: 2 },
        tags: ['ammo', 'rifle'],
    },
    ammo_shotgun: {
        id: 'ammo_shotgun',
        name: 'Патроны 12 калибра',
        description: 'Картечь для ружья. Упаковка 8 шт.',
        kind: 'consumable',
        rarity: 'uncommon',
        icon: '🔫',
        imageUrl: '/images/снаряга/патроныружьё.png',
        baseStats: { weight: 0.4, width: 1, height: 1 },
        tags: ['ammo', 'shotgun'],
    },
    ammo_sniper_mag: {
        id: 'ammo_sniper_mag',
        name: 'Магазин снайперский',
        description: 'Магазин для СВД. 10 патронов повышенной точности.',
        kind: 'consumable',
        rarity: 'rare',
        icon: '🎯',
        imageUrl: '/images/снаряга/патронвинтовка.png',
        baseStats: { weight: 0.4, width: 1, height: 1 },
        tags: ['ammo', 'sniper'],
    },

    // ============ GEAR - FIELD ============
    chest_rig: {
        id: 'chest_rig',
        name: 'Разгрузка',
        description: 'Тактическая разгрузка с карманами для магазинов.',
        kind: 'rig',
        rarity: 'uncommon',
        icon: '🦺',
        imageUrl: '/images/снаряга/Разгрузка.jpg',
        baseStats: {
            weight: 1.5,
            width: 3,
            height: 2,
            capacity: 8,
            containerConfig: { width: 4, height: 2, name: 'Chest Rig' },
        },
        tags: ['rig'],
    },
    holster: {
        id: 'holster',
        name: 'Кобура',
        description: 'Кобура для пистолета. Быстрое извлечение.',
        kind: 'rig',
        rarity: 'common',
        icon: '🔫',
        imageUrl: '/images/снаряга/Кобура.png',
        baseStats: { weight: 0.3, width: 1, height: 2 },
        tags: ['rig', 'holster'],
    },
    canteen: {
        id: 'canteen',
        name: 'Фляга',
        description: 'Ёмкость для воды. Необходима для длительных походов.',
        kind: 'consumable',
        rarity: 'common',
        icon: '🫗',
        imageUrl: '/images/снаряга/Фляга.jpg',
        baseStats: { weight: 0.8, width: 1, height: 1 },
        tags: ['sustenance', 'water'],
    },
    map_tactical: {
        id: 'map_tactical',
        name: 'Тактическая карта',
        description: 'Детальная карта местности с пометками.',
        kind: 'misc',
        rarity: 'uncommon',
        icon: '🗺',
        imageUrl: '/images/снаряга/карта.jpg',
        baseStats: { weight: 0.1, width: 2, height: 1 },
        tags: ['navigation'],
    },
    shovel: {
        id: 'shovel',
        name: 'Сапёрная лопата',
        description: 'Универсальный инструмент. Можно копать, рубить и бить.',
        kind: 'weapon',
        rarity: 'common',
        icon: '⛏',
        imageUrl: '/images/снаряга/лопата.jpg',
        baseStats: { damage: 8, weight: 1.0, width: 1, height: 2, maxDurability: 60 },
        tags: ['melee', 'tool'],
    },
}

/** Array format for iteration (backwards compatible with server seeds) */
export const ITEM_TEMPLATES_ARRAY = Object.values(ITEM_TEMPLATES)

/** Lookup by ID */
export const ITEM_TEMPLATES_BY_ID = ITEM_TEMPLATES
