/**
 * Unified Item Templates
 * =====================================================
 * Single source of truth for all item definitions.
 * Used by both client and server (server copies during build).
 * =====================================================
 */

import type { ItemTemplate } from './itemTypes'

export const ITEM_TEMPLATES: Record<string, ItemTemplate> = {
    // ============ WEAPONS - MELEE ============
    rusty_sword: {
        id: 'rusty_sword',
        name: 'Ржавый меч',
        description: 'Старый железный меч, зазубренный и тупой. Лучше, чем голыми руками.',
        kind: 'weapon',
        rarity: 'common',
        icon: '⚔️',
        baseStats: { damage: 12, weight: 2.5, width: 1, height: 3, maxDurability: 50 },
        tags: ['melee', 'slashing'],
    },
    rusty_pipe: {
        id: 'rusty_pipe',
        name: 'Ржавая труба',
        description: 'Тяжелая, корродированная железная труба. Грубо, но эффективно.',
        kind: 'weapon',
        rarity: 'common',
        icon: 'pipe',
        baseStats: { damage: 8, weight: 2.0, width: 1, height: 3, maxDurability: 40 },
        tags: ['melee', 'blunt'],
        combatWeaponId: 'rusty_pipe',
    },
    lead_pipe: {
        id: 'lead_pipe',
        name: 'Свинцовая труба',
        description: 'Тяжелая, корродированная свинцовая труба. Грубо, но эффективно.',
        kind: 'weapon',
        rarity: 'common',
        icon: 'pipe',
        baseStats: { damage: 8, weight: 3.0, width: 1, height: 3, maxDurability: 50 },
        tags: ['melee', 'crushing'],
    },
    kitchen_knife: {
        id: 'kitchen_knife',
        name: 'Кухонный нож',
        description: 'Стандартный кухонный нож. Острый, но хрупкий.',
        kind: 'weapon',
        rarity: 'common',
        icon: '🔪',
        baseStats: { damage: 5, weight: 0.5, width: 1, height: 2, maxDurability: 30 },
        tags: ['melee', 'piercing'],
    },
    sledgehammer: {
        id: 'sledgehammer',
        name: 'Кувалда',
        description: 'Тяжелый промышленный инструмент. Разрушительный удар.',
        kind: 'weapon',
        rarity: 'uncommon',
        icon: '🔨',
        baseStats: { damage: 14, weight: 8.0, width: 2, height: 4, maxDurability: 80 },
        tags: ['melee', 'crushing', 'two_handed'],
    },
    broken_bottle: {
        id: 'broken_bottle',
        name: 'Разбитая бутылка',
        description: 'Острые осколки стекла. Вызывает кровотечение.',
        kind: 'weapon',
        rarity: 'common',
        icon: '🍾',
        baseStats: { damage: 4, weight: 0.2, width: 1, height: 1, maxDurability: 5 },
        tags: ['melee', 'slashing'],
    },
    knife: {
        id: 'knife',
        name: 'Выкидной нож',
        description: 'Скрытный и острый.',
        kind: 'weapon',
        rarity: 'common',
        icon: '🗡',
        baseStats: { damage: 6, weight: 0.5, width: 1, height: 1, maxDurability: 40 },
        tags: ['melee', 'stealth'],
        combatWeaponId: 'combat_knife',
    },
    wrench: {
        id: 'wrench',
        name: 'Разводной ключ',
        description: 'Хорош для ремонта, или чтобы что-нибудь сломать.',
        kind: 'weapon',
        rarity: 'common',
        icon: '🔧',
        baseStats: { damage: 10, weight: 2, width: 1, height: 2, maxDurability: 60 },
        tags: ['melee', 'tool'],
        combatWeaponId: 'wrench',
    },

    // ============ WEAPONS - RANGED ============
    glock_19: {
        id: 'glock_19',
        name: 'Glock 19',
        description: 'Надежный 9мм пистолет. Стандартное вооружение.',
        kind: 'weapon',
        rarity: 'rare',
        icon: '🔫',
        baseStats: { damage: 10, weight: 1.5, width: 2, height: 2, maxDurability: 100 },
        tags: ['ranged', 'ballistic', 'pistol'],
        combatWeaponId: 'glock_19',
    },
    pistol_pm: {
        id: 'pistol_pm',
        name: 'Пистолет ПМ',
        description: 'Пистолет Макарова. Надежное личное оружие.',
        kind: 'weapon',
        rarity: 'common',
        icon: '🔫',
        baseStats: { damage: 8, weight: 1.5, width: 2, height: 1, maxDurability: 100 },
        tags: ['ranged', 'pistol'],
        combatWeaponId: 'makarov',
    },
    sawed_off_shotgun: {
        id: 'sawed_off_shotgun',
        name: 'Обрез',
        description: 'Модифицирован для ближнего боя. Большой разброс.',
        kind: 'weapon',
        rarity: 'rare',
        icon: '💥',
        baseStats: { damage: 18, weight: 2.5, width: 3, height: 2, maxDurability: 80 },
        tags: ['ranged', 'ballistic', 'shotgun'],
        combatWeaponId: 'sawed_off',
    },
    rifle_ak74: {
        id: 'rifle_ak74',
        name: 'AK-74',
        description: 'Надежная штурмовая винтовка. Калибр 5.45мм.',
        kind: 'weapon',
        rarity: 'rare',
        icon: '🔫',
        baseStats: { damage: 25, weight: 3.5, width: 3, height: 2, maxDurability: 90 },
        tags: ['ranged', 'rifle', 'two_handed'],
        combatWeaponId: 'ak_74',
    },

    // ============ ARMOR ============
    vest_police: {
        id: 'vest_police',
        name: 'Полицейский жилет',
        description: 'Стандартный кевларовый жилет. Обеспечивает неплохую защиту.',
        kind: 'armor',
        rarity: 'uncommon',
        icon: '🦺',
        baseStats: { defense: 15, weight: 4, width: 3, height: 3, maxDurability: 80 },
        tags: ['armor'],
    },
    helmet_police: {
        id: 'helmet_police',
        name: 'Шлем спецназа',
        description: 'Тяжелый шлем с забралом.',
        kind: 'armor',
        rarity: 'uncommon',
        icon: '⛑',
        baseStats: { defense: 10, weight: 2, width: 2, height: 2, maxDurability: 60 },
        tags: ['armor', 'head'],
    },
    jacket_hidden: {
        id: 'jacket_hidden',
        name: 'Куртка контрабандиста',
        description: 'Куртка со скрытой подкладкой.',
        kind: 'armor',
        rarity: 'uncommon',
        icon: '🧥',
        baseStats: { defense: 3, weight: 2, width: 2, height: 2 },
        tags: ['clothing', 'stealth'],
    },

    // ============ CLOTHING ============
    scout_jacket: {
        id: 'scout_jacket',
        name: 'Куртка разведчика',
        description: 'Легкая куртка со скрытыми карманами. Любима бегунами.',
        kind: 'clothing',
        rarity: 'rare',
        icon: '🧥',
        baseStats: { defense: 2, weight: 1.5, width: 2, height: 2 },
        tags: ['clothing', 'stealth'],
    },
    clothing_basic: {
        id: 'clothing_basic',
        name: 'Поношенная одежда',
        description: 'Простая, удобная одежда. Видала виды.',
        kind: 'clothing',
        rarity: 'common',
        icon: '👕',
        baseStats: { weight: 1, width: 2, height: 2, defense: 1 },
        tags: ['clothing'],
    },
    trousers_basic: {
        id: 'trousers_basic',
        name: 'Штаны карго',
        description: 'Прочные штаны с множеством карманов.',
        kind: 'clothing',
        rarity: 'common',
        icon: '👖',
        baseStats: { weight: 1, width: 2, height: 2, defense: 1 },
        tags: ['clothing'],
    },

    // ============ BACKPACKS / RIGS ============
    backpack_medic: {
        id: 'backpack_medic',
        name: 'Медицинская сумка',
        description: 'Специализированный рюкзак с отсеками для медикаментов.',
        kind: 'backpack',
        rarity: 'uncommon',
        icon: '🎒',
        baseStats: {
            weight: 1.5,
            width: 2,
            height: 2,
            capacity: 16,
            containerConfig: { width: 4, height: 4, name: 'Medic Bag' },
        },
        tags: ['backpack'],
    },
    belt_tool: {
        id: 'belt_tool',
        name: 'Пояс с инструментами',
        description: 'Держит инструменты под рукой.',
        kind: 'rig',
        rarity: 'common',
        icon: '🛠',
        baseStats: {
            weight: 1,
            width: 2,
            height: 1,
            capacity: 4,
            containerConfig: { width: 4, height: 1, name: 'Tool Belt' },
        },
        tags: ['rig'],
    },

    // ============ CONSUMABLES ============
    field_medkit: {
        id: 'field_medkit',
        name: 'Полевая аптечка',
        description: 'Стандартный медицинский набор. Восстанавливает HP и останавливает кровотечение.',
        kind: 'consumable',
        rarity: 'uncommon',
        icon: '⛑',
        baseStats: { weight: 1.2, width: 2, height: 2 },
        tags: ['healing'],
    },
    medkit: {
        id: 'medkit',
        name: 'Аптечка первой помощи',
        description: 'Необходима для лечения ран.',
        kind: 'consumable',
        rarity: 'uncommon',
        icon: '⛑',
        baseStats: { weight: 1, width: 1, height: 1 },
        tags: ['healing'],
    },
    bandage: {
        id: 'bandage',
        name: 'Грязный бинт',
        description: 'Лучше, чем ничего, но есть риск инфекции.',
        kind: 'consumable',
        rarity: 'common',
        icon: 'bandage',
        baseStats: { weight: 0.1, width: 1, height: 1 },
        tags: ['healing'],
    },
    pills: {
        id: 'pills',
        name: 'Обезболивающее',
        description: 'Временное облегчение боли.',
        kind: 'consumable',
        rarity: 'common',
        icon: '💊',
        baseStats: { weight: 0.1, width: 1, height: 1 },
        tags: ['healing'],
    },
    ration_pack: {
        id: 'ration_pack',
        name: 'Сухпаек',
        description: 'Позволит продержаться день на границе. На вкус как картон.',
        kind: 'consumable',
        rarity: 'common',
        icon: '🍞',
        baseStats: { weight: 0.6, width: 1, height: 1 },
        tags: ['sustenance'],
    },
    canned_food: {
        id: 'canned_food',
        name: 'Консервированные бобы',
        description: 'Истек срок годности в 2012. Съедобно, наверное.',
        kind: 'consumable',
        rarity: 'common',
        icon: 'can',
        baseStats: { weight: 0.5, width: 1, height: 1 },
        tags: ['sustenance'],
    },

    // ============ ARTIFACTS ============
    mica_shard: {
        id: 'mica_shard',
        name: 'Осколок слюды',
        description: 'Слабо светится при приближении аномалий. Теплый на ощупь.',
        kind: 'artifact',
        rarity: 'epic',
        icon: '🜁',
        baseStats: { weight: 0.2, width: 1, height: 1 },
        tags: ['artifact', 'detection'],
    },

    // ============ MISC / MATERIALS ============
    badge: {
        id: 'badge',
        name: 'Полицейский значок',
        description: 'Потускневший значок. Власть осталась в прошлом.',
        kind: 'misc',
        rarity: 'common',
        icon: '👮',
        baseStats: { weight: 0.1, width: 1, height: 1 },
        tags: ['misc'],
    },
    scrap: {
        id: 'scrap',
        name: 'Металлолом',
        description: 'Полезен для крафта и ремонта.',
        kind: 'misc',
        rarity: 'common',
        icon: '⚙️',
        baseStats: { weight: 0.5, width: 1, height: 1 },
        tags: ['material'],
    },
    cash: {
        id: 'cash',
        name: 'Кредиты',
        description: 'Валюта старого мира. Все еще имеет ценность для некоторых.',
        kind: 'misc',
        rarity: 'common',
        icon: '💵',
        baseStats: { weight: 0, width: 1, height: 1 },
        tags: ['currency'],
    },
}

/** Array format for iteration (backwards compatible with server seeds) */
export const ITEM_TEMPLATES_ARRAY = Object.values(ITEM_TEMPLATES)

/** Lookup by ID */
export const ITEM_TEMPLATES_BY_ID = ITEM_TEMPLATES
